export const usersData = [
  {
    "email": "aarav.sharma@yopmail.com",
    "firstName": "Aarav",
    "lastName": "Sharma",
    "lastname": "Sharma",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "admin",
    "createdAt": "2026-01-05T09:12:00+05:30"
  },
  {
    "email": "vivaan.patel@yopmail.com",
    "firstName": "Vivaan",
    "lastName": "Patel",
    "lastname": "Patel",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "Frontend developer",
    "role": "user",
    "createdAt": "2026-01-07T14:25:10+05:30"
  },
  {
    "email": "aditya.verma@yopmail.com",
    "firstName": "Aditya",
    "lastName": "Verma",
    "lastname": "Verma",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-01-10T11:02:45+05:30"
  },
  {
    "email": "krishna.reddy@yopmail.com",
    "firstName": "Krishna",
    "lastName": "Reddy",
    "lastname": "Reddy",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "Backend engineer",
    "role": "admin",
    "createdAt": "2026-01-12T16:40:22+05:30"
  },
  {
    "email": "arjun.nair@yopmail.com",
    "firstName": "Arjun",
    "lastName": "Nair",
    "lastname": "Nair",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-01-15T08:18:03+05:30"
  },
  {
    "email": "ishaan.mehra@yopmail.com",
    "firstName": "Ishaan",
    "lastName": "Mehra",
    "lastname": "Mehra",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "UI designer",
    "role": "user",
    "createdAt": "2026-01-18T13:55:31+05:30"
  },
  {
    "email": "rohan.kapoor@yopmail.com",
    "firstName": "Rohan",
    "lastName": "Kapoor",
    "lastname": "Kapoor",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "admin",
    "createdAt": "2026-01-20T19:22:17+05:30"
  },
  {
    "email": "siddharth.jain@yopmail.com",
    "firstName": "Siddharth",
    "lastName": "Jain",
    "lastname": "Jain",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-01-22T10:05:49+05:30"
  },
  {
    "email": "karan.malhotra@yopmail.com",
    "firstName": "Karan",
    "lastName": "Malhotra",
    "lastname": "Malhotra",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "QA tester",
    "role": "user",
    "createdAt": "2026-01-25T15:48:12+05:30"
  },
  {
    "email": "rahul.singh@yopmail.com",
    "firstName": "Rahul",
    "lastName": "Singh",
    "lastname": "Singh",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "admin",
    "createdAt": "2026-01-28T09:31:55+05:30"
  },
  {
    "email": "manish.yadav@yopmail.com",
    "firstName": "Manish",
    "lastName": "Yadav",
    "lastname": "Yadav",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-01-30T18:03:41+05:30"
  },
  {
    "email": "deepak.chauhan@yopmail.com",
    "firstName": "Deepak",
    "lastName": "Chauhan",
    "lastname": "Chauhan",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "Support",
    "role": "user",
    "createdAt": "2026-02-01T12:44:19+05:30"
  },
  {
    "email": "naveen.kumar@yopmail.com",
    "firstName": "Naveen",
    "lastName": "Kumar",
    "lastname": "Kumar",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "admin",
    "createdAt": "2026-02-03T07:50:00+05:30"
  },
  {
    "email": "ankit.gupta@yopmail.com",
    "firstName": "Ankit",
    "lastName": "Gupta",
    "lastname": "Gupta",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-04T14:29:27+05:30"
  },
  {
    "email": "sumit.agrawal@yopmail.com",
    "firstName": "Sumit",
    "lastName": "Agrawal",
    "lastname": "Agrawal",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "Manager",
    "role": "admin",
    "createdAt": "2026-02-05T20:11:09+05:30"
  },
  {
    "email": "tarun.saxena@yopmail.com",
    "firstName": "Tarun",
    "lastName": "Saxena",
    "lastname": "Saxena",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-06T10:00:33+05:30"
  },
  {
    "email": "prateek.bansal@yopmail.com",
    "firstName": "Prateek",
    "lastName": "Bansal",
    "lastname": "Bansal",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-07T16:16:45+05:30"
  },
  {
    "email": "lokesh.mittal@yopmail.com",
    "firstName": "Lokesh",
    "lastName": "Mittal",
    "lastname": "Mittal",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "Accounts",
    "role": "admin",
    "createdAt": "2026-02-08T09:09:59+05:30"
  },
  {
    "email": "harsh.vora@yopmail.com",
    "firstName": "Harsh",
    "lastName": "Vora",
    "lastname": "Vora",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-09T13:37:18+05:30"
  },
  {
    "email": "jay.shah@yopmail.com",
    "firstName": "Jay",
    "lastName": "Shah",
    "lastname": "Shah",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-10T17:58:22+05:30"
  },
  {
    "email": "meet.patel@yopmail.com",
    "firstName": "Meet",
    "lastName": "Patel",
    "lastname": "Patel",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "Mobile dev",
    "role": "admin",
    "createdAt": "2026-02-11T08:26:41+05:30"
  },
  {
    "email": "dhruv.desai@yopmail.com",
    "firstName": "Dhruv",
    "lastName": "Desai",
    "lastname": "Desai",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-12T12:13:55+05:30"
  },
  {
    "email": "yash.trivedi@yopmail.com",
    "firstName": "Yash",
    "lastName": "Trivedi",
    "lastname": "Trivedi",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-13T19:45:02+05:30"
  },
  {
    "email": "parth.dave@yopmail.com",
    "firstName": "Parth",
    "lastName": "Dave",
    "lastname": "Dave",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "Intern",
    "role": "user",
    "createdAt": "2026-02-14T09:52:28+05:30"
  },
  {
    "email": "kunal.soni@yopmail.com",
    "firstName": "Kunal",
    "lastName": "Soni",
    "lastname": "Soni",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "admin",
    "createdAt": "2026-02-15T15:07:39+05:30"
  },
  {
    "email": "hemant.prajapati@yopmail.com",
    "firstName": "Hemant",
    "lastName": "Prajapati",
    "lastname": "Prajapati",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-16T11:33:11+05:30"
  },
  {
    "email": "rakesh.tiwari@yopmail.com",
    "firstName": "Rakesh",
    "lastName": "Tiwari",
    "lastname": "Tiwari",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "HR",
    "role": "admin",
    "createdAt": "2026-02-17T18:21:57+05:30"
  },
  {
    "email": "pankaj.mishra@yopmail.com",
    "firstName": "Pankaj",
    "lastName": "Mishra",
    "lastname": "Mishra",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-18T09:10:03+05:30"
  },
  {
    "email": "sunil.joshi@yopmail.com",
    "firstName": "Sunil",
    "lastName": "Joshi",
    "lastname": "Joshi",
    "password": "Abc@123",
    "profilePhoto": "",
    "bio": "",
    "role": "user",
    "createdAt": "2026-02-18T14:22:44+05:30"
  }
]
